grupo = m_gru_azul;
reloj_anima = 0;
paso_anima = 0;
mi_agua_x = x; // evita salida a tierra
mi_agua_y = y;
reloj_ataque = m_reloj_ataque;
vida_max = s_get_vida(object_index);
vida = vida_max;
fuego = irandom(m_fuegos_ani - 1);
paso_disparo = -1;
reloj_disparo = 0;
reloj_activo = 0; // evita error
