s_invisi_recursos();
grupo = m_gru_azul;
helice_ang = random(360);
ext_mineral = 0;
ext_madera = 0;
reloj_produccion = 0;
vida_max = s_get_vida(object_index);
vida = vida_max;
fuego = irandom(m_fuegos_ani - 1);
s_extractores();
s_audio(a_construir, x, y);
